version: '3.8'

services:
    sharebook-front-next:
        container_name: sharebook-front-next
        ports:
            - '3000:3000'
        build:
            context: .
            dockerfile: Dockerfile.dev.linux
        volumes:
            - .:/appdev
        restart: always
# [Yarn] yarn dev-docker-compose
# [NPM] npm run dev-docker-compose
# [Terminal]: docker-compose -f .\docker-compose.dev.yml up --build
# [Git Bash]: docker-compose -f docker-compose.dev.yml up --build
