name: Run Sonar Cloud

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    install-sonarcloud:
        runs-on: ubuntu-latest

        steps:
            - name: Get files
              uses: actions/checkout@v2
            - name: Use Node.js 16.c
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: Install packages
              run: |
                  if [ -e yarn.lock ]; then
                  yarn install --frozen-lockfile
                  elif [ -e package-lock.json ]; then
                  npm ci
                  else
                  npm i
                  fi
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
