name: Run Unit Tests with Jest

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    install-unit-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Get files
              uses: actions/checkout@v2
            - name: Use Node.js 16.c
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - name: Install packages
              run: |
                  if [ -e yarn.lock ]; then
                  yarn install --frozen-lockfile
                  elif [ -e package-lock.json ]; then
                  npm ci
                  else
                  npm i
                  fi
            - name: Run tests
              run: npm run test --coverage
